package types

type Payment struct {
	AgrmId             int           `json:"agrm_id"`
	AgrmNum            string        `json:"agrm_num"`
	Amount             float64       `json:"amount"`
	AmountCur          float64       `json:"amount_cur"`
	CancelDate         interface{}   `json:"cancel_date"`
	CardNumber         interface{}   `json:"card_number"`
	CashCode           int           `json:"cash_code"`
	ClassId            int           `json:"class_id"`
	ClassName          string        `json:"class_name"`
	Comment            string        `json:"comment"`
	CurId              int           `json:"cur_id"`
	CurSymb            string        `json:"cur_symb"`
	ExtraStatus        int           `json:"extra_status"`
	FromAgrmId         interface{}   `json:"from_agrm_id"`
	FromAgrmNumber     interface{}   `json:"from_agrm_number"`
	Inn                string        `json:"inn"`
	IsEps              int           `json:"is_eps"`
	LocalDate          string        `json:"local_date"`
	LocalTimestamp     int           `json:"local_timestamp"`
	MgrDescr           string        `json:"mgr_descr"`
	MgrFio             string        `json:"mgr_fio"`
	MgrLogin           string        `json:"mgr_login"`
	ModPerson          int           `json:"mod_person"`
	OperId             int           `json:"oper_id"`
	OperName           string        `json:"oper_name"`
	OrderId            interface{}   `json:"order_id"`
	OrderNum           interface{}   `json:"order_num"`
	Orders             []interface{} `json:"orders"`
	OrgPaymentId       interface{}   `json:"org_payment_id"`
	OrganizationId     int           `json:"organization_id"`
	OrganizationName   string        `json:"organization_name"`
	ParentRecordId     interface{}   `json:"parent_record_id"`
	PayCode            interface{}   `json:"pay_code"`
	PayDate            string        `json:"pay_date"`
	PaymentOrderNumber interface{}   `json:"payment_order_number"`
	PeriodDate         interface{}   `json:"period_date"`
	Receipt            string        `json:"receipt"`
	RecordId           int           `json:"record_id"`
	RevCount           int           `json:"rev_count"`
	RevNo              int           `json:"rev_no"`
	Status             int           `json:"status"`
	Timestamp          int           `json:"timestamp"`
	Uid                int           `json:"uid"`
	Uprs               []interface{} `json:"uprs"`
	UserLogin          string        `json:"user_login"`
	UserName           string        `json:"user_name"`
	Uuid               interface{}   `json:"uuid"`
}
