package types

type Tariff struct {
	TarId             int           `json:"tar_id"`
	ActBlock          int           `json:"act_block"`
	Additional        int           `json:"additional"`
	Addons            []interface{} `json:"addons"`
	AdmBlockRent      float64       `json:"adm_block_rent"`
	Archive           int           `json:"archive"`
	Assigned          int           `json:"assigned"`
	AvailableFl       int           `json:"available_fl"`
	AvailableUl       int           `json:"available_ul"`
	BlockRent         float64       `json:"block_rent"`
	BlockRentDuration int           `json:"block_rent_duration"`
	ChargeIncoming    int           `json:"charge_incoming"`
	CheckActiveHours  int           `json:"check_active_hours"`
	CoefHigh          float64       `json:"coef_high"`
	CoefLow           float64       `json:"coef_low"`
	CommonIncludes    int           `json:"common_includes"`
	CurId             int           `json:"cur_id"`
	CurName           string        `json:"cur_name"`
	DailyRent         int           `json:"daily_rent"`
	Descr             string        `json:"descr"`
	DescrFull         string        `json:"descr_full"`
	DynRoute          int           `json:"dyn_route"`
	DynamicRent       int           `json:"dynamic_rent"`
	LastModDate       int           `json:"last_mod_date"`
	Link              string        `json:"link"`
	NdsAbove          int           `json:"nds_above"`
	PricePlan         int           `json:"price_plan"`
	Rent              float64       `json:"rent"`
	RentAsService     int           `json:"rent_as_service"`
	RentMultiply      int           `json:"rent_multiply"`
	SaleDictionaryId  int           `json:"sale_dictionary_id"`
	ServiceType       int           `json:"service_type"`
	Shape             int           `json:"shape"`
	ShapePrior        int           `json:"shape_prior"`
	Symbol            string        `json:"symbol"`
	TimeMark          LBTimeMark    `json:"time_mark"`
	TraffLimit        int           `json:"traff_limit"`
	TraffLimitPer     int           `json:"traff_limit_per"`
	TraffType         int           `json:"traff_type"`
	Type              int           `json:"type"`
	Unavailable       int           `json:"unavailable"`
	UseCommonIncludes int           `json:"use_common_includes"`
	Used              int           `json:"used"`
	UsrBlockRent      float64       `json:"usr_block_rent"`
	Uuid              string        `json:"uuid"`
	VoipBlockLocal    int           `json:"voip_block_local"`
}
